# Change these first
owner: vichaos # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

sites:
  - name: http_inspect
    url: https://ea5b-184-22-193-217.ngrok.io
  - name: Sentry
    url: https://sentry9-th.line-apps.com/_health/
  - name: OAplus
    url: https://oaplus.line.biz/health
  - name: OAplus - Developers 
    url: https://developers-oaplus.line.biz/
    expectedStatusCodes:
      - 404
  - name: OA Plus - LIFF
    url: https://web-api-oaplus.line.me
    expectedStatusCodes:
      - 404
  - name: OA Plus - mobile API
    url: https://api-oaplus-mobile.line-apps.com/account/v1/accounts
    expectedStatusCodes:
      - 401
  - name: OA Plus - partner API
    url: https://api-oaplus-partner.line-apps.com/v1/jwks/jwks.json
  - name: SC
    url: https://shop.line.me/
    expectedStatusCodes:
      - 302
  - name: SC storefront productend
    url: https://shop.line.me/@024azltq/product/319384970
  - name: SC storefront shopend
    url: https://shop.line.me/@024azltq
  - name: MyShop API with Authorization Header
    url: https://developers-oaplus.line.biz/myshop/api/health
    headers:
      - "x-api-key: $MYSHOP_API_KEYS"
  - name: Horoscope
    url: https://horoscope.line.me
  - name: TodayShowcase
    url: https://todayshowcase.line.me
  - name: Melody
    url: https://melody.line.me
  - name: Sticker Channel API
    url: https://sticker-channel-api.line.me/monitor/l7check

status-website:
  theme: dark
  robotsText: "User-agent: * \n Disallow: /"
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
user-agent: $OWNER
